__include__: [
  '../dataset/aitod_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/d3rdetr_hgnetv2.yml',
]

output_dir: ./output/dome_s_aitod


D3RDETR:
  backbone: HGNetv2

HGNetv2:
  name: 'B0'
  return_idx: [0, 1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

D3RDETRTransformer:
  num_layers: 3  # 5 6
  num_levels: 4
  eval_idx: -1  # -2 -3
  feat_channels: [256, 256, 256, 256]
  feat_strides: [4, 8, 16, 32]
  num_points: [4, 4, 4, 4]
  min_num_select: 300
  max_num_select: 1500

HybridEncoder:
  in_channels: [64, 256, 512, 1024]
  feat_strides: [4, 8, 16, 32]
  use_encoder_idx: [3] # Only not deformable
  use_hybrid: True
  num_encoder_layers: 1
  use_deformable: False
  enc_n_points: 6 # Only deformable
  hidden_dim: 256
  depth_mult: .33
  expansion: 0.5
  num_feature_levels: 4
  use_defe: True
  defe_type: 'light'
  use_mwas: True # Only if use_defe
  mwas_window_size: 5

D3RDETRCriterion:
  defe_density_map_weight: 1

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00005
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00005
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


lr_scheduler:
  type: MultiStepLR
  milestones: [80, 120]
  gamma: 0.8

lr_warmup_scheduler:
  warmup_duration: 1000

# Increase to search for the optimal ema
epoches: 145
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 120
  collate_fn:
    stop_epoch: 120
    ema_restart_decay: 0.9999
    base_size_repeat: 2
  total_batch_size: 4
val_dataloader:
  total_batch_size: 4

val_interval: 4